import Navbar from "./Navbar";
import Head from "next/head";
import {
  Box,
  Paper,
  BottomNavigation,
  BottomNavigationAction,
} from "@mui/material";
import { useEffect, useState } from "react";
import useMediaQuery from "@mui/material/useMediaQuery";
import StorefrontIcon from "@mui/icons-material/Storefront";
import ReceiptIcon from "@mui/icons-material/Receipt";
import AccountCircleIcon from "@mui/icons-material/AccountCircle";
import FavoriteIcon from "@mui/icons-material/Favorite";
import { useRouter } from "next/router";

const Layout = ({ children }) => {
  const [value, setValue] = useState(null);
  const matches = useMediaQuery("(max-width:900px)");
  const router = useRouter();

  useEffect(() => {
    if (router.route.includes("store")) {
      setValue(0);
    } else if (router.route.includes("favorite")) {
      setValue(1);
    } else if (router.route.includes("transaction")) {
      setValue(2);
    } else {
      setValue(3);
    }

    // switch (router.route) {
    //   case router.route.includes("favorite"):
    //     setValue(1);
    //     break;
    //   case router.route.includes("transaction"):
    //     setValue(2);
    //     break;
    //   case router.route.includes("account"):
    //     setValue(3);
    //     break;

    //   default:
    //     setValue(0);
    //     break;
    // }
  }, []);

  return (
    <div className="content">
      <Head>
        <title>SuperOne Accessories | User Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {children}
      {matches && (
        <Paper
          sx={{ position: "fixed", bottom: 0, left: 0, right: 0 }}
          elevation={3}
        >
          <BottomNavigation
            showLabels
            value={value}
            onChange={(event, newValue) => {
              setValue(newValue);
              switch (newValue) {
                case 1:
                  router.push("/favorite");
                  break;
                case 2:
                  router.push("/transaction");
                  break;
                case 3:
                  router.push("/account");
                  break;

                default:
                  router.push("/store");
                  break;
              }
            }}
          >
            <BottomNavigationAction label="Store" icon={<StorefrontIcon />} />
            <BottomNavigationAction label="Favorite" icon={<FavoriteIcon />} />

            <BottomNavigationAction
              label="Transactions"
              icon={<ReceiptIcon />}
            />

            <BottomNavigationAction
              label="Account"
              icon={<AccountCircleIcon />}
            />
          </BottomNavigation>
        </Paper>
      )}
    </div>
  );
};

export default Layout;
